### ISSUE TITLE
Use scale or dimensions from e.g. Hires. Fix

### ISSUE THREAD

**Issue by kJLRtqYn** [AndreyRGW/sd-webui-fsr-integration#3]
I was wondering, if it would be possible to integrate the flexible scaling capabilities of FidelityFX_CLI in this extension.

As far as I understand FidelityFX_CLI is capable to get different scalings or dimensions as input and do an upscale based on these parameters.

My understanding so far is, that this could be possible, if you can get the hr_scale and/or the hr_resize_x, txt2img_hr_resize_y values from Automatic1111. Sadly my programing skills aren't advanced enough to get these values, thus I'm not able to implement this.

I'm not sure if and how this is possible, but I would find it an interesting option when FidelityFX_CLI does the scaling based on input parameters.

**Comment by AndreyRGW** [comment]
> I was wondering, if it would be possible to integrate the flexible scaling capabilities of FidelityFX_CLI in this extension.
> 
> As far as I understand FidelityFX_CLI is capable to get different scalings or dimensions as input and do an upscale based on these parameters.
> 
> My understanding so far is, that this could be possible, if you can get the hr_scale and/or the hr_resize_x, txt2img_hr_resize_y values from Automatic1111. Sadly my programing skills aren't advanced enough to get these values, thus I'm not able to implement this.
> 
> I'm not sure if and how this is possible, but I would find it an interesting option when FidelityFX_CLI does the scaling based on input parameters.

I have added a new upscaler option — FidelityFX Universal to the list of upscalers, which can take values from hr_scale, x, y.

I won't close the issue just yet. Please update the extension and check if everything works correctly.

**Comment by kJLRtqYn** [comment]
I gave it a quick test and it seems to work flawlessly. I've tested it with several models, scale and resolution variations and had no issues.
Thanks a lot for the great work!
